import pandas as pd

configfile: "config/config.yaml"

samples = pd.read_csv(config["samples"], sep="\t").set_index("sample", drop=False)

def get_reads(wildcards):
    return samples.loc[wildcards.sample, "reads"]

rule all:
    input:
        # 1. Decontamination Outputs (Cek hasil bersih)
        expand("results/final_genome/{sample}_final_clean.fasta", sample=samples.index),
        expand("results/final_genome/{sample}_rejected_ids.txt", sample=samples.index),
        
        # 2. QC Outputs (Cek kualitas assembly awal vs akhir jika mau)
        expand("results/qc/quast/{sample}/report.html", sample=samples.index),
        expand("results/qc/busco/{sample}/short_summary.txt", sample=samples.index),
        
        # 3. Repeats (EDTA)
        expand("results/repeats/{sample}/genome.fasta.mod.MAKER.masked", sample=samples.index),
        
        # 4. Annotation (Liftoff + Galba + Stats)
        expand("results/annotation/{sample}_liftoff.gff3", sample=samples.index),
        expand("results/annotation/{sample}_galba.gff3", sample=samples.index),
        expand("results/annotation/{sample}_stats.txt", sample=samples.index)

# Load Rules
include: "rules/assembly.smk"
include: "rules/assessment.smk"
include: "rules/decontamination.smk" # <-- New Rule File
include: "rules/repeats.smk"
include: "rules/annotation.smk"