import pandas as pd

configfile: "config/config.yaml"

samples = pd.read_csv(config["samples"], sep="\t").set_index("sample", drop=False)

def get_reads(wildcards):
    return samples.loc[wildcards.sample, "reads"]

rule all:
    input:
        # 1. Assembly & Polishing
        expand("results/medaka/{sample}/consensus.fasta", sample=samples.index),
        
        # 2. Post-Assembly QC (Report Kualitas)
        expand("results/qc/quast/{sample}/report.html", sample=samples.index),
        expand("results/qc/busco/{sample}/short_summary.txt", sample=samples.index),
        
        # 3. Annotation
        expand("results/annotation/{sample}.liftoff.gff3", sample=samples.index),
        
        # 4. Masked Genome
        expand("results/repeats/{sample}_masked.fasta", sample=samples.index)

include: "rules/assembly.smk"
include: "rules/assessment.smk" # QC Pasca-Assembly
include: "rules/repeats.smk"
include: "rules/annotation.smk"